version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: pallets_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: joelrojas123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  
      - /app/pallets_app/static 
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - PYTHONPATH=/app
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DB_NAME=pallets_db
      - DB_USER=postgres
      - DB_PASSWORD=joelrojas123
      - DB_HOST=db
      - DB_PORT=5432

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: npm start
    depends_on:
      - backend

volumes:
  postgres_data:
