# Generated by Django 5.2.1 on 2025-05-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(default='INGRESO', max_length=20)),
                ('estado', models.CharField(choices=[('POR_RECIBIR', 'Por Recibir'), ('RECIBIDO', 'Recibido')], max_length=20)),
                ('origen', models.CharField(max_length=100)),
                ('desde_empresa', models.CharField(max_length=100)),
                ('hacia_empresa', models.CharField(max_length=100)),
            ],
        ),
    ]
